#!/bin/bash
export PATH=`pwd`:`pwd`/src:`pwd`/bin:$PATH
export CD=`pwd`
if [ ! -f jdk-lin/lib/modules ]; then
  cd jdk-lin/lib
  echo "n" | unzip -o modules.zip
  cd $CD
fi
jdk-lin/bin/java -Dsun.java2d.uiScale=1.0 -jar game.jar &

