cdx: Go.java Scorer.java Contest.java GameParameters.java Player.java \
		Run.java PlayerDB.java ReadDB.java SaveDB.java CheckServices.java \
		HTTPQuery.java ContestTimer.java Run.java DynamicListener.java \
		Output.java Messages.java MakeStandings.java ReadParm.java \
		ReadPlayerDB.java
	rm -f *.class
	../../jdk-lin/bin/javac Run.java
	../../jdk-lin/bin/jar cfm cdx-contest.jar .perms-run.txt *.class
	rm -f *.class
