#!/bin/bash
cd ../contest
export EASYRSA_BATCH=1
./easyrsa init-pki
./easyrsa build-ca nopass >& /dev/null
echo "CA key and cert made" > progress
./easyrsa gen-req server nopass >& /dev/null
./easyrsa sign-req server server >& /dev/null
echo "server key and cert made" >> progress
sleep 1
rm -fr ./server/ccd
mkdir ./server/ccd
rm -f ./server/ipp.txt
i="0"
while [ $i -lt $1 ]
do
	p=$[$i+100]
	./workaround client"$i" < ../config/game-id.txt
	./easyrsa sign-req client client"$i" >& /dev/null
	echo "client"$i" key and cert made" >> progress
	echo "ifconfig-push 10.8.0."$p" 255.255.255.0" > ./server/ccd/client"$i"
	echo "client"$i",10.8.0."$p >> ./server/ipp.txt
	sleep 1
   i=$[$i+1]
done
chmod -R go-w server/ccd
chmod -R go-w server/keys
sleep 1
echo "beginning diffie-hellman parameters" >> progress
./bin/openssl dhparam -out keys/dh2048.pem 2048 >& /dev/null
